---
- name: Install and Configure Tomcat on FreeBSD
  hosts: freebsd
  become: yes
  tasks:

    - name: Install Tomcat
      ansible.builtin.pkgng:
        name: "tomcat9"
        state: present

    - name: Enable Tomcat in rc.conf
      ansible.builtin.lineinfile:
        path: /etc/rc.conf
        line: 'tomcat9_enable="YES"'
        state: present

    - name: Start Tomcat service
      ansible.builtin.service:
        name: tomcat9
        state: started
