# Tomcat Installation playbook for cross platform please type your hostname here before running the playbook

- name: Install for cross platform
  hosts: localhost
  remote_user: tomcat
  become: yes
  roles:
    - role: tomcatx
      vars:
        tomcat_location: /opt/
        test_urls:
          - test_url: "{{ ansible_facts['fqdn'] }}:8080/"
          - test_url: "{{ ansible_facts['fqdn'] }}:8080/admin/"
        backup_location: /tmp/
        files:
          - file_name: admin
        new_wars:
          - war_src: admin.war
            war_dest: admin.war
