# Tomcat Installation playbook for cross platform please type your hostname here before running the playbook

- name: Install for cross platform
  hosts: freebsd
  become: yes
  roles:
    - role: tomcatx
      vars:
        tomcat_location: /opt/
