# Tomcat Installation playbook for cross platform please type your hostname here before running the playbook

- name: Install for cross platform
  hosts: suse
  #remote_user: tomcat
  become: yes
  roles:
    - role: tomcatx
      vars:
        tomcat_webapps_location: /opt/tomcat10/webapps/
        #tomcat_webapps_location: /usr/local/apache-tomcat-9.0/webapps/ #FREEBSD
        tomcat_location: /opt/
        test_urls:
          - test_url: "{{ ansible_facts['fqdn'] }}:8080/"
          #- test_url: "{{ ansible_facts['fqdn'] }}:8080/admin/"
        backup_location: /tmp/
        files:
          - file_name: test
        new_wars:
          - war_src: test.war
            war_dest: test.war
