- name: Block to verify Enterprise linux versions
  block:
    - name: Verify OS Type and version
      debug:
        msg:
          - "Host OS Family is = {{ ansible_facts['os_family'] }}"
          - "Host Distribution Version is = {{ ansible_facts['distribution_version'] }}"

    - name: Making sure all Neccessary packages are present
      apt:
        name:
          - curl
          - tar
          - git
          - ufw
        state: present

    - name: Install Tomcat and all dependencies
      apt:
        name: tomcat10
        state: present

    - name: Check Java Installation and Version
      command: "java -version"
      register: version

    - name: Displaying Java Installation and Version
      debug:
        var: version.stderr_lines

    - name: Download tomcat packages
      copy:
        src: apache-tomcat-10.0.27.tar.gz
        dest: "{{ tomcat_location }}apache-tomcat-10.0.27.tar.gz"

    - name: Extract tar Archive
      unarchive:
        src: "{{ tomcat_location }}apache-tomcat-10.0.27.tar.gz"
        dest: "{{ tomcat_location }}"
        remote_src: true

    - name: Rename Folder apache-tomcat-10.0.27 to tomcat10
      command: "mv {{ tomcat_location }}apache-tomcat-10.0.27 {{ tomcat_location }}tomcat10"
      ignore_errors: true

    - name: Create tomcat User
      user:
        name: tomcat
        state: present

    - name: Set tomcat Ownership and file Permissions 
      file:
        path: "{{ tomcat_location }}tomcat10"
        owner: tomcat
        group: tomcat
        recurse: true

    - name: Create tomcat service file
      template:
        src: tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service

    - name: Reload systemd
      systemd:
        daemon-reload: true

    - name: Enable unfiltered firewall
      community.general.ufw:
        rule: allow
        port: 8080

    - name: Start tomcat service
      service:
        name: tomcat
        state: started
        enabled: true

    - name: Wait for Tomcat to load.
      wait_for:
        msg: "Please Wait"
        timeout: 7

    - name: Load Tomcat URL
      uri:
        url: "http://{{ ansible_facts['fqdn'] }}:8080"
        status_code: 200
      register: url_status

    - name: Display Installation complete Message
      debug:
        msg: "Tomcat v10 Installation Complete on {{ ansible_facts['fqdn'] }}"
      when: url_status.status == 200
  when: 
    - ansible_facts['os_family'] == "Debian"