# tasks file for tomcat installation on FreeBSD OS
- name: Block to verify Enterprise linux versions
  block:
    - name: Verify OS Type and version
      debug:
        msg:
          - "Host OS Family is = {{ ansible_facts['os_family'] }}"
          - "Host Distribution Version is = {{ ansible_facts['distribution_version'] }}"

    - name: Install java openjdk
      pkgng:
        name: openjdk11-11.0.24+8.1_1
        state: present

    - name: Install Neccessary Packages
      pkgng:
        name:
          - gtar
          - xtar
          - git
          - zip
        state: present

    - name: Check Java Installation and Version
      command: "java -version"
      register: version

    - name: Displaying Java Installation and Version
      debug:
        var: version.stderr_lines

    - name: Install Tomcat
      ansible.builtin.pkgng:
        name: "tomcat9"
        state: present
    
    - name: Enable Tomcat in rc.conf
      ansible.builtin.lineinfile:
        path: /etc/rc.conf
        line: 'tomcat9_enable="YES"'
        state: present
    
    - name: Start Tomcat service
      ansible.builtin.service:
        name: tomcat9
        state: started
    
    - name: Wait for Tomcat to load.
      ansible.builtin.wait_for:
        msg: "Please Wait"
        timeout: 7
    
    - name: Load Tomcat URL
      ansible.builtin.uri:
        url: "http://{{ ansible_facts['fqdn'] }}:8080"
        status_code: 200    
      register: url_status
    
    - name: Display Installation complete Message
      ansible.builtin.debug:
        msg: "Tomcat v10 Installation Complete on {{ ansible_facts['fqdn'] }}"
      when: url_status.status == 200
  when: 
    - ansible_facts['os_family'] == "FreeBSD"


- name: Deploy a JAVA application
  block:
    - name: Test URL status from local machine
      uri:
        url: "http://{{ item.test_url }}"
        status_code: 200
      ignore_errors: yes
      loop: "{{ test_urls }}"
      delegate_to: localhost

    - name: Stop the tomcat service
      service:
        name: tomcat9
        state: stopped

    - name: Backup the previous version of the WAR files to /tmp directory
      copy:
        src: '{{ tomcat_webapps_location }}{{ item.file_name }}.war'
        dest: '{{ backup_location }}{{ item.file_name }}.war'
        remote_src: yes
      loop: "{{ files }}"
      ignore_errors: yes

    - name: Remove the previous version of the WAR and expanded directory
      file:
        path: "{{ tomcat_webapps_location }}{{ item.file_name }}.war"
        state: absent
      loop: "{{ files }}"

    - name: Remove the previous version of the expanded directory
      file:
        path: '{{ tomcat_webapps_location }}{{ item.file_name }}'
        state: absent
      loop: "{{ files }}"

    - name: Verify the previous contents are gone
      command: "ls -al {{ tomcat_webapps_location }}"
      register: list_status

    - name: Display list
      debug:
        var: list_status.stdout_lines

    - name: Copy Deployment file to Document Root
      copy:
        src: '{{ item.war_src }}'
        dest: '{{ tomcat_webapps_location }}{{ item.war_dest }}'
      loop: "{{ new_wars }}"


    - name: Set file permissions on Document Root
      file: 
        path: '{{ tomcat_webapps_location }}{{ item.war_dest }}'
        mode: 0660
        owner: tomcat
        group: tomcat
      loop: "{{ new_wars }}"

    - name: Start tomcat service
      service:
        name: tomcat9
        state: restarted

    - name: wait for 10 second for URL to load
      wait_for:
        timeout: 10

    - name: Verify JAVA Application is deployed
      command: 'ls -al {{ tomcat_webapps_location }}'
      register: list_status

    - name: Verify WAR file permissions
      debug:
        var: list_status.stdout_lines
  

- name: URL status block
  block:
    - name: Run URL status
      uri:  
        url: 'http://{{ item.test_url }}'
        return_content: yes
        status_code: 200
      loop: "{{ test_urls }}"
      delegate_to: localhost
    - name: Display deployment status
      debug:
        msg: "WAR file Deployment successfully on {{ ansible_facts['fqdn'] }}"