# tasks file for tomcat installation on FreeBSD OS
- name: Block to verify Enterprise linux versions
  block:
    - name: Verify OS Type and version
      debug:
        msg:
          - "Host OS Family is = {{ ansible_facts['os_family'] }}"
          - "Host Distribution Version is = {{ ansible_facts['distribution_version'] }}"

    - name: Install java openjdk
      pkgng:
        name: openjdk11-11.0.24+8.1_1
        state: present

    - name: Install Neccessary Packages
      pkgng:
        name:
          - gtar
          - xtar
          - git
          - zip
        state: present

    - name: Check Java Installation and Version
      command: "java -version"
      register: version

    - name: Displaying Java Installation and Version
      debug:
        var: version.stderr_lines

    - name: Install Tomcat
      ansible.builtin.pkgng:
        name: "tomcat9"
        state: present
    
    - name: Enable Tomcat in rc.conf
      ansible.builtin.lineinfile:
        path: /etc/rc.conf
        line: 'tomcat9_enable="YES"'
        state: present
    
    - name: Start Tomcat service
      ansible.builtin.service:
        name: tomcat9
        state: started
    
    - name: Wait for Tomcat to load.
      ansible.builtin.wait_for:
        msg: "Please Wait"
        timeout: 7
    
    - name: Load Tomcat URL
      ansible.builtin.uri:
        url: "http://{{ ansible_facts['fqdn'] }}:8080"
        status_code: 200    
      register: url_status
    
    - name: Display Installation complete Message
      ansible.builtin.debug:
        msg: "Tomcat v10 Installation Complete on {{ ansible_facts['fqdn'] }}"
      when: url_status.status == 200
  when: 
    - ansible_facts['os_family'] == "FreeBSD"