# Tasks for tomcat installation across platforms

- name: Running Red Hat tasks
  include_tasks: RedHat.yml
  when: 
    - ansible_facts['os_family'] == "RedHat"

- name: Running Debian tasks
  include_tasks: debian.yml
  when:
    - ansible_facts['os_family'] == "Debian"

- name: Running FreeBSD tasks
  include_tasks: freebsd2.yml
  when:
    - ansible_facts['os_family'] == "FreeBSD"

  
- name: Running OpenSUSE tasks
  include_tasks: opensuse.yml
  when:
      - ansible_facts['os_family'] == "Suse"