# Tasks for tomcat installation across platforms

- name: Running Red Hat Tasks
  include_tasks: RedHat.yml
  when: 
    - ansible_facts['os_family'] == "RedHat"

- name: Running Debian Tasks
  include_tasks: debian.yml
  when:
    - ansible_facts['os_family'] == "Debian"

- name: Running FreeBSD Tasks
  include_tasks: freebsd.yml
  when:
    - ansible_facts['os_family'] == "FreeBSD"
  
- name: Running OpenSUSE Tasks
  include_tasks: opensuse.yml
  when:
      - ansible_facts['os_family'] == "Suse"

- name: Running Windows Tasks
  include_tasks: Windows.yml
  when:
    - ansible_facts['os_family'] == "Windows"